/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ulb.mis.view;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JCheckBox;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import ulb.mis.controller.SicknessJpaController;
import ulb.mis.model.Sickness;

/**
 *
 * @author fanny
 */
public class SymptomsWindow extends javax.swing.JFrame {
    private final EntityManagerFactory emfac = Persistence.createEntityManagerFactory("MISproject_PU");
    private final SicknessJpaController sicknessCtrl = new SicknessJpaController(emfac);
    
    private static final Logger LOGGER = LogManager.getLogger(CreatePatientAccount.class.getName());

    int a = 0;
    int b = 0;
    /**
     * Creates new form symp
     */
    
    public SymptomsWindow() {
        initComponents();
        
        
        java.util.List<Sickness> sicknesses = sicknessCtrl.findSicknessEntities();
        setLayout(null); // Utiliser le null layout
        
        for(int i =0; i < sicknesses.size(); i++){
            javax.swing.JCheckBox checkBox = new javax.swing.JCheckBox(sicknesses.get(i).getSymptom1());           
            checkBox.setBounds(100*a, 50*b, 100, 25); // Définissez les coordonnées et la taille de la checkbox
            add(checkBox);
            if (b!=12){
                b= b+1;
            }
            else{
                b=0;
                a = a+1;
            }
            javax.swing.JCheckBox checkBox2 = new javax.swing.JCheckBox(sicknesses.get(i).getSymptom2());           
            checkBox2.setBounds(100*a, 50*b, 100, 25);
            add(checkBox2);
            if (b!=12){
                b= b+1;
            }
            else{
                b=0;
                a = a+1;
            }
            javax.swing.JCheckBox checkBox3 = new javax.swing.JCheckBox(sicknesses.get(i).getSymptom3());           
            checkBox3.setBounds(100*a, 50*b, 100, 25);
            add(checkBox3);
            if (b!=12){
                b= b+1;
            }
            else{
                b=0;
                a = a+1;
            }
            javax.swing.JCheckBox checkBox4 = new javax.swing.JCheckBox(sicknesses.get(i).getSymptom4());           
            checkBox4.setBounds(100*a, 50*b, 100, 25);
            add(checkBox4);
            if (b!=12){
                b= b+1;
            }
            else{
                b=0;
                a = a+1;
            }
        }
        // Ajouter d'autres checkboxes avec des positions personnalisées...

        setSize(500, 600); // Définir la taille souhaitée pour la fenêtre
        setResizable(false); // Empêcher le redimensionnement de la fenêtre

        setPreferredSize(getSize()); // Définir la taille préférée pour la fenêtre
        pack();
    }
      
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 613, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
